---
title: "p8105_hw3_jh4054"
author: "Joy Hsu"
date: "10/12/2018"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
  
---

This R Markdown for HW3 reinforces skills from Data Visualization and Exploratory Data Analysis

### 0. Setup

Load packages and set chunk options

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(viridis)
library(janitor)
library(p8105.datasets)

knitr::opts_chunk$set(
  warning = FALSE, 
  message = FALSE, 
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

### Problem 1

```{r}
brfss_df = p8105.datasets::brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>% 
  select(
    -class, -topic, -question, -sample_size, 
    -c(confidence_limit_low:geo_location)) %>% 
  separate(locationdesc, into = c("rem1", "county"), sep = 5) %>% 
  select(-rem1) %>% 
  rename(state = locationabbr, proportion = data_value) %>% 
  mutate(response = factor(response, levels = c("Excellent","Very good", "Good", "Fair", "Poor"))) %>% 
  arrange(year, state, county)
```

```{r}

```


